name: Metrics
on:
  # 每天 6:48 自动更新
  schedule: [{cron: "48 6 * * *"}]
  # 支持手动触发更新
  workflow_dispatch:
  # 往这个仓库推代码时也触发更新
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.Metrics }}

          # 基础设置
          user: Highsun
          template: classic
          
          # 【精简】base 设为空，隐藏头像、用户信息等重复内容
          base: ""

          # 核心功能：语言统计插件
          plugin_languages: yes
          # 过滤掉非编程语言的辅助文件
          plugin_languages_ignored: html, css, tex, mako, dockerfile, markdown, json, yaml
          # 【跳过仓库】屏蔽部分仓库
          plugin_languages_skipped: snk
          
          # 排行与细节设置
          plugin_languages_details: percentage            # 显示百分比
          plugin_languages_limit: 8                       # 最多显示 8 种语言
          plugin_languages_sections: most-used            # 显示最常用的语言
          plugin_languages_threshold: 0%                  # 只有一点点占比的语言也显示
          
          # 美化与时区
          plugin_languages_colors: github                 # 使用 GitHub 官方语言颜色
          config_timezone: Asia/Shanghai
